name: npm-build

# Only trigger on:
# - main branch
# - PR or Pull Request event types
# - Exclude Docusaurus files: this file, docs/** and website/**
on:
  push:
    branches:
      - release/**
    paths-ignore:
      - '.github/workflows/docusaurus.yml'
  pull_request:
    branches:
      - main
      - release/**
    paths-ignore:
      - '.github/workflows/docusaurus.yml'
jobs:
# JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    # Set job outputs to values from the filter step
    outputs:
      builtFiles: ${{ steps.filter.outputs.builtFiles }}
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36
      id: filter
      with:
        filters: |
          builtFiles:
            - '.eslint*'
            - 'src/**'
            - 'schemas/**'
            - 'package-lock.json'
            - 'package.json'
            - 'rollup.config.js'
            - 's2tQuicktypeUtil.js'
            - 'tsconfig.json'
            - '.github/workflows/package.yml'
            
  package-build:
    name: Build on Node ${{ matrix.node }} and ${{ matrix.os }}
    needs: changes
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [20]
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout repo
        if: ${{ needs.changes.outputs.builtFiles == 'true' }}
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Use Node ${{ matrix.node }}
        if: ${{ needs.changes.outputs.builtFiles == 'true' }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        if: ${{ needs.changes.outputs.builtFiles == 'true' }}
        uses: bahmutov/npm-install@2509f13e8485d88340a789a3f7ca11aaac47c9fc #v1.8.36

      - name: Lint
        if: ${{ needs.changes.outputs.builtFiles == 'true' }}
        run: npm run lint

      - name: Test
        if: ${{ needs.changes.outputs.builtFiles == 'true' }}
        run:  npm run test --ci --coverage --maxWorkers=2

      - name: Build
        if: ${{ needs.changes.outputs.builtFiles == 'true' }}
        run:  npm run build

      - name: Checkout repo
        if: ${{ needs.changes.outputs.builtFiles == 'false' }}
        run: 'echo "Build steps skipped as no relevant changes were detected"'


  package-publish:
    if: ${{ github.event_name == 'push' && needs.changes.outputs.builtFiles == 'true'}}
    needs: [changes,package-build]
    name: Publish package to ${{ matrix.name }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    strategy:
      matrix:
       include:
         - name: NPM
           registry: https://registry.npmjs.org
           token-name: NPM_TOKEN
         - name: GitHub
           registry: https://npm.pkg.github.com
           token-name: GITHUB_TOKEN
    steps:
    - name: Checkout repo
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7


    - name: Configure Node
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version: 20
        registry-url: ${{ matrix.registry }}

    - name: Check package version
      id: check-version
      uses: tehpsalmist/npm-publish-status-action@deb911186cfe5134094f49183364da10a986e4e7
      with:
        node-version: 20
        registry-url: ${{ matrix.registry }}
        
    # Disabled when switching from PostHog/check-package-version as the new lib 
    #   just tells you if your version exists or not 
    # - name: Package version info
    #   run: |
    #     echo "Committed version: ${{ steps.check-version.outputs.committed-version }}"
    #     echo "Published version: ${{ steps.check-version.published-version }}"
    #     echo "Is version new: ${{ steps.check-version.outputs.is-new-version }}"

    - name: Report already published status
      if: steps.check-version.outputs.exists == '1' 
      run: 'echo "package version already exists in registry ${{ matrix.registry }}"'
      
    - name: Report not yet published status
      if: steps.check-version.outputs.exists == '0' 
      run: 'echo "package version does not exist in registry ${{ matrix.registry }}, publishing..."'
      
    - name: Install dependencies
      if: steps.check-version.outputs.exists == '0' 
      uses: bahmutov/npm-install@2509f13e8485d88340a789a3f7ca11aaac47c9fc #v1.8.36

    - name: Publish
      if: steps.check-version.outputs.exists == '0' 
      run:  npm publish --provenance --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets[matrix.token-name] }}
