name: npm-build

# Only trigger on:
# - main branch
# - PR or Pull Request event types
# - Exclide Docusaurus files: this file, docs/** and website/**
on:
  push:
    branches:
      - main
      - release/**
    paths-ignore:
      - '.github/workflows/docusaurus.yml'
      - 'docs/**'
      - 'website/**'
  pull_request:
    branches:
      - main
      - release/*
    paths-ignore:
      - '.github/workflows/docusaurus.yml'
      - 'docs/**'
      - 'website/**'
jobs:
  package-build:
    name: Build on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [20]
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        uses: bahmutov/npm-install@2509f13e8485d88340a789a3f7ca11aaac47c9fc #v1.8.36

      - name: Lint
        run: npm run lint

      - name: Test
        run:  npm run test --ci --coverage --maxWorkers=2

      - name: Build
        run:  npm run build

  package-publish:
    if: ${{ github.event_name == 'push' }}
    needs: package-build
    name: Publish package to ${{ matrix.name }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    strategy:
      matrix:
       include:
        #  - name: NPM
        #    registry: https://registry.npmjs.org
        #    token-name: NPM_TOKEN
         - name: GitHub
           registry: https://npm.pkg.github.com
           token-name: GITHUB_TOKEN
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Configure Node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        registry-url: ${{ matrix.registry }}

    # hacked to always publish to github for testing - DO NOT MERGE
      
    - name: Install dependencies
      uses: bahmutov/npm-install@2509f13e8485d88340a789a3f7ca11aaac47c9fc #v1.8.36

    - name: Publish
      run:  npm publish --provenance --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets[matrix.token-name] }}
